# Default values for spring-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: deiandrei/devops-fur-techniker
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  type: ClusterIP
  port: 1234
  
ingress:
  enabled: false
  host: localhost
  path: /apis/demo
  annotations: {
    ingress.kubernetes.io/rewrite-target: "/",
    kubernetes.io/ingress.class: "nginx"
  }